import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, Bike, Bus, Heart, Leaf, MapPin, Navigation, Save, Search, Settings, Train, Zap } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { motion } from 'framer-motion';
import { bikeHubs, routeOptions, serviceUpdates, sustainabilityTrend, travelModes } from './data/travelData';
import { estimateJourney, modeById, scoreRoute } from './utils/calc';
import { loadSettings, saveSettings } from './utils/storage';
import './styles.css';

const iconMap = { bus:Bus, rail:Train, cycle:Bike, walk:MapPin, mixed:Navigation };

function App(){
  const [tab,setTab]=useState('home');
  const [settings,setSettings]=useState(loadSettings);
  const [distance,setDistance]=useState(settings.lastEstimate.distance);
  const [mode,setMode]=useState(settings.lastEstimate.mode);
  const [from,setFrom]=useState('St Mary’s Campus');
  const [to,setTo]=useState('Twickenham Station');
  const estimate=useMemo(()=>estimateJourney(Number(distance)||0, mode),[distance,mode]);
  const ranked=useMemo(()=>routeOptions.map(r=>({...r, aiScore:scoreRoute(r, settings.preferredMode)})).sort((a,b)=>b.aiScore-a.aiScore),[settings.preferredMode]);
  useEffect(()=>saveSettings(settings),[settings]);
  function updateSettings(patch){ setSettings(prev=>({...prev,...patch})); }
  function saveCurrentEstimate(){ updateSettings({lastEstimate:{distance:Number(distance),mode}}); }
  function toggleFavourite(id){ updateSettings({favourites: settings.favourites.includes(id)?settings.favourites.filter(x=>x!==id):[...settings.favourites,id]}); }
  return <>
    <a className="skip" href="#content">Skip to content</a>
    <header className="hero">
      <nav><div className="brand"><span>SM</span> Urban Mobility Hub</div><div className="navlinks">{['home','planner','dashboard','sustainability','alerts'].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x}</button>)}</div></nav>
      <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="heroGrid">
        <div><p className="eyebrow">St Mary’s travel information web app</p><h1>Plan realistic, lower-carbon journeys across campus and the city.</h1><p className="lead">Compare bus, rail, walking, cycling and mixed-mode routes with live-style updates, saved journeys, alerts and personalised recommendations.</p><button className="primary" onClick={()=>setTab('planner')}>Plan a journey <Search size={17}/></button></div>
        <div className="glass"><div className="pulse"><Zap/> Best recommendation</div><h2>{ranked[0].from} → {ranked[0].to}</h2><p>{ranked[0].time} min · £{ranked[0].cost.toFixed(2)} · reliability {ranked[0].reliability}%</p><progress value={ranked[0].aiScore} max="100"/><small>Intelligent score based on reliability, cost, convenience and your preferred mode.</small></div>
      </motion.div>
    </header>
    <main id="content">
      {tab==='home'&&<Home setTab={setTab} />}
      {tab==='planner'&&<Planner {...{distance,setDistance,mode,setMode,estimate,saveCurrentEstimate,from,setFrom,to,setTo,ranked,toggleFavourite,settings}} />}
      {tab==='dashboard'&&<Dashboard settings={settings} updateSettings={updateSettings} ranked={ranked} toggleFavourite={toggleFavourite}/>} 
      {tab==='sustainability'&&<Sustainability settings={settings} updateSettings={updateSettings}/>} 
      {tab==='alerts'&&<Alerts settings={settings} updateSettings={updateSettings}/>} 
    </main>
    <footer>Built as a front-end React artefact. Data is simulated API-style for reliability, privacy and assessment reproducibility.</footer>
  </>;
}
function Card({children,className=''}){return <motion.section initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className={`card ${className}`}>{children}</motion.section>}
function Home({setTab}){return <div className="wrap grid3"><Card><MapPin/><h2>Clear journey guidance</h2><p>Start with a route, compare travel modes, check costs and understand likely time, reliability and accessibility before you leave.</p><button onClick={()=>setTab('planner')}>Open planner</button></Card><Card><AlertTriangle/><h2>Service awareness</h2><p>Mock live disruption notices show realistic delays, closures and platform changes without depending on unstable external services.</p><button onClick={()=>setTab('alerts')}>View updates</button></Card><Card><Leaf/><h2>Sustainability goals</h2><p>Track cycling, walking and carbon saved with visual analytics and weekly goals designed for everyday urban travel decisions.</p><button onClick={()=>setTab('sustainability')}>Track goals</button></Card><section className="wide"><h2>Travel modes</h2><div className="modeGrid">{travelModes.map(m=>{const Icon=iconMap[m.id];return <article key={m.id} className="mode"><Icon/><h3>{m.name}</h3><p><b>Best for:</b> {m.benefits.join(', ')}.</p><p><b>Limitations:</b> {m.limits.join(', ')}.</p><span>{m.accessibility} accessibility · {m.speed} km/h average</span></article>})}</div></section></div>}
function Planner({distance,setDistance,mode,setMode,estimate,saveCurrentEstimate,from,setFrom,to,setTo,ranked,toggleFavourite,settings}){const [compare,setCompare]=useState(['bus','cycle']); return <div className="wrap"><section className="split"><Card><h2>Fare and impact estimator</h2><label>Distance in km<input type="number" min="0" step="0.1" value={distance} onChange={e=>setDistance(e.target.value)}/></label><label>Travel mode<select value={mode} onChange={e=>setMode(e.target.value)}>{travelModes.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="result"><strong>£{estimate.low}–£{estimate.high}</strong><span>{estimate.minutes} minutes · {estimate.co2}g CO₂</span></div><button onClick={saveCurrentEstimate}><Save size={16}/> Save input</button></Card><Card><h2>Journey comparison</h2><div className="row"><select value={compare[0]} onChange={e=>setCompare([e.target.value,compare[1]])}>{travelModes.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><select value={compare[1]} onChange={e=>setCompare([compare[0],e.target.value])}>{travelModes.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div><Compare a={compare[0]} b={compare[1]} distance={Number(distance)||1}/></Card></section><Card><h2>Route planner</h2><div className="row"><input aria-label="From" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="To" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="routes">{ranked.map(r=><RouteCard key={r.id} r={r} fav={settings.favourites.includes(r.id)} toggleFavourite={toggleFavourite}/>)}</div></Card></div>}
function Compare({a,b,distance}){const ea=estimateJourney(distance,a), eb=estimateJourney(distance,b); return <div className="compare"><div><b>{modeById(a).icon} {modeById(a).name}</b><p>£{ea.low}–£{ea.high}</p><p>{ea.minutes} min · {ea.co2}g CO₂</p></div><div><b>{modeById(b).icon} {modeById(b).name}</b><p>£{eb.low}–£{eb.high}</p><p>{eb.minutes} min · {eb.co2}g CO₂</p></div></div>}
function RouteCard({r,fav,toggleFavourite}){return <article className="route"><div><h3>{r.from} → {r.to}</h3><p>{r.modes.map(m=>modeById(m).name).join(' + ')} · {r.distance} km · {r.time} min · £{r.cost.toFixed(2)}</p><small>{r.steps.join(' → ')}</small></div><div className="routeMeta"><span>{r.aiScore}/100</span><button aria-label="save favourite" onClick={()=>toggleFavourite(r.id)}><Heart fill={fav?'currentColor':'none'}/></button></div></article>}
function Dashboard({settings,updateSettings,ranked,toggleFavourite}){const favRoutes=ranked.filter(r=>settings.favourites.includes(r.id));return <div className="wrap split"><Card><Settings/><h2>Personal travel profile</h2><label>Preferred mode<select value={settings.preferredMode} onChange={e=>updateSettings({preferredMode:e.target.value})}>{travelModes.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label>Typical travel time<input value={settings.typicalTime||'08:30'} onChange={e=>updateSettings({typicalTime:e.target.value})}/></label><p className="tip">Recommendation engine prioritises routes matching your mode, reliability and current alerts.</p></Card><Card><h2>Saved journeys</h2>{favRoutes.map(r=><RouteCard key={r.id} r={r} fav toggleFavourite={toggleFavourite}/>)}{!favRoutes.length&&<p>No saved journeys yet.</p>}</Card><Card className="wide"><h2>Nearby stops and shared mobility</h2><div className="modeGrid">{bikeHubs.map(b=><article className="mode" key={b.name}><Bike/><h3>{b.name}</h3><p>{b.bikes} bikes · {b.ebikes} e-bikes · {b.spaces} spaces</p><span>{b.demand}</span></article>)}</div></Card></div>}
function Sustainability({settings,updateSettings}){const total=sustainabilityTrend.reduce((s,d)=>s+d.saved,0).toFixed(1);return <div className="wrap split"><Card><Leaf/><h2>Carbon analytics</h2><p className="big">{total} kg CO₂e saved this week</p><label>Weekly carbon goal kg<input type="number" value={settings.carbonGoal} onChange={e=>updateSettings({carbonGoal:Number(e.target.value)})}/></label><progress value={total} max={settings.carbonGoal}/></Card><Card><h2>Trend visualisation</h2><ResponsiveContainer width="100%" height={250}><AreaChart data={sustainabilityTrend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Area dataKey="saved"/></AreaChart></ResponsiveContainer></Card><Card className="wide"><h2>Active travel progress</h2><ResponsiveContainer width="100%" height={260}><BarChart data={sustainabilityTrend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey="cycling"/><Bar dataKey="walking"/></BarChart></ResponsiveContainer></Card></div>}
function Alerts({settings,updateSettings}){const [newAlert,setNewAlert]=useState('Rail A'); function add(){ if(newAlert&&!settings.alerts.includes(newAlert)) updateSettings({alerts:[...settings.alerts,newAlert]}); } return <div className="wrap split"><Card><AlertTriangle/><h2>Live-style service updates</h2>{serviceUpdates.map(u=><article className={`notice ${u.severity.toLowerCase()}`} key={u.id}><b>{u.severity}: {u.line}</b><h3>{u.title}</h3><p>{u.message}</p><small>Updated {u.updated}</small></article>)}</Card><Card><h2>Custom route alerts</h2><div className="row"><input value={newAlert} onChange={e=>setNewAlert(e.target.value)} aria-label="Line or route"/><button onClick={add}>Add alert</button></div>{settings.alerts.map(a=><p className="pill" key={a}>{a}<button onClick={()=>updateSettings({alerts:settings.alerts.filter(x=>x!==a)})}>×</button></p>)}<p className="tip">In a production build, this layer can connect to push notifications, email or transport-webhook services.</p></Card></div>}
createRoot(document.getElementById('root')).render(<App/>);
